services:
  recommendation-service:
    image: noopur17/retail-recommendation-service:latest
    container_name: retail-recommendation-service
    ports:
      - "8001:8000"

  content-intelligence-service:
    image: noopur17/retail-content-intelligence-service:latest
    container_name: retail-content-intelligence-service
    ports:
      - "8002:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    image: noopur17/retail-ai-frontend:latest
    container_name: retail-ai-frontend
    ports:
      - "5173:5173"
    depends_on:
      - recommendation-service
      - content-intelligence-service